@lastId=80
@limit=2
### create product
POST http://localhost:3000/api/products
Authorization: Bearer {{$global.accessToken}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="barcode"

123456780
--WebKitFormBoundary
Content-Disposition: form-data; name="productName"

Sample Product new
--WebKitFormBoundary
Content-Disposition: form-data; name="qty"

100
--WebKitFormBoundary
Content-Disposition: form-data; name="price"

25000
--WebKitFormBoundary
Content-Disposition: form-data; name="kategoryId"

1
--WebKitFormBoundary
Content-Disposition: form-data; name="supplierId"

5
--WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="example.jpg"
Content-Type: image/png

< ./example.jpg
--WebKitFormBoundary--

### get all product
GET http://localhost:3000/api/products
Authorization: Bearer {{$global.accessToken}}

### get product by id
GET http://localhost:3000/api/products/1
Authorization: Bearer {{$global.accessToken}}

### get product by category
GET http://localhost:3000/api/products/category/1
Authorization: Bearer {{$global.accessToken}}

### update product
PUT http://localhost:3000/api/products/1
Authorization: Bearer {{$global.accessToken}}
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="barcode"

123456789
--WebKitFormBoundary
Content-Disposition: form-data; name="productName"

Sample Product
--WebKitFormBoundary
Content-Disposition: form-data; name="qty"

100
--WebKitFormBoundary
Content-Disposition: form-data; name="price"

25000
--WebKitFormBoundary
Content-Disposition: form-data; name="kategoryId"

1
--WebKitFormBoundary
Content-Disposition: form-data; name="supplierId"

5
--WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="example.jpg"
Content-Type: image/png

< ./example.jpg
--WebKitFormBoundary--

### delete product
DELETE http://localhost:3000/api/products/2
Authorization: Bearer {{$global.accessToken}}

### generate pdf
GET http://localhost:3000/api/products-pdf
Authorization: Bearer {{$global.accessToken}}

### generate excel
GET http://localhost:3000/api/products-excel
Authorization: Bearer {{$global.accessToken}}