### create user
POST http://localhost:3000/api/users
Content-Type: application/json
{
  "name":"Teguh Bagas M",
  "userName":"teguh",
  "password":"teguh",
  "confirmPassword":"teguh",
  "role":"manager"
}

### user login
POST http://localhost:3000/api/users/login
Content-Type: application/json
{
  "userName":"teguh",
  "password":"teguh"
}
### user login
POST http://localhost:3000/api/users/logout
Content-Type: application/json
Authorization: Bearer {{$global.accessToken}}
{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlck5hbWUiOiJ0ZWd1aCIsInBhc3N3b3JkIjoieHh4eHh4eHh4eHh4eHh4eHh4IiwibmFtZSI6IlRlZ3VoIEJhZ2FzIE0iLCJyb2xlIjoia2FzaXIiLCJpYXQiOjE3MzYwODg1MzYsImV4cCI6MTczNjE3NDkzNn0.fmVQRCMmF8N2p59qzLtbxlHQRjOjC7O92N0SycQwv3w"
}

{{
  $global.accessToken=JSON.parse(response.body).acessToken;
  $global.refreshToken=JSON.parse(response.body).refreshToken;
}}

### update user
PUT http://localhost:3000/api/users/2
Content-Type: application/json
Authorization: Bearer {{$global.accessToken}}
{
  "name":"Teguh Bagmar",
  "userName":"bagmar",
  "password":"bagmar",
  "confirmPassword":"bagmar",
  "role":"kasir"
}

### delete user
DELETE http://localhost:3000/api/users/3
Content-Type: application/json
Authorization: Bearer {{$global.accessToken}}

### get all user
GET http://localhost:3000/api/users
Authorization: Bearer {{$global.accessToken}}

### get user by id
GET http://localhost:3000/api/users/2
Authorization: Bearer {{$global.accessToken}}

### refresh token
GET http://localhost:3000/api/users/refresh
Authorization: Bearer {{$global.refreshToken}}

{{
  $global.accessToken=JSON.parse(response.body).acessToken;
  $global.refreshToken=JSON.parse(response.body).refreshToken;
}}